{{- if .Values.config.authorizer.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: authorizer-webhook
  {{- /* Only include annotations in manual cert mode (certProvisionMode=manual) */ -}}
  {{- if and (eq .Values.config.server.webhooks.certProvisionMode "manual") .Values.webhooks.authorizerWebhook.annotations }}
  annotations:
    {{- toYaml .Values.webhooks.authorizerWebhook.annotations | nindent 4 }}
  {{- end }}
  labels:
{{- include "operator.authorizer.webhook.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      {{- if .Values.webhooks.caBundle }}
      caBundle: {{ .Values.webhooks.caBundle }}
      {{- end }}
      service:
        name: {{ required ".Values.service.name is required" .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: /webhooks/authorizer-webhook
        port: {{ required ".Values.config.server.webhooks.port" .Values.config.server.webhooks.port }}
    failurePolicy: Fail
    matchPolicy: Exact
    name: authorizer.webhooks.grove.io
    namespaceSelector: { }
    sideEffects: None
    objectSelector:
      matchLabels:
        app.kubernetes.io/managed-by: grove-operator
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - UPDATE
          - DELETE
        resources:
          - secrets
          - serviceaccounts
          - services
        scope: "Namespaced"
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - UPDATE
        resources:
          - pods
        scope: "Namespaced"
      - apiGroups:
          - "rbac.authorization.k8s.io"
        apiVersions:
          - v1
        operations:
          - UPDATE
          - DELETE
        resources:
          - roles
          - rolebindings
        scope: "Namespaced"
      - apiGroups:
          - "autoscaling"
        apiVersions:
          - v1
          - v2
        operations:
          - UPDATE
          - DELETE
        resources:
          - horizontalpodautoscalers
        scope: "Namespaced"
      - apiGroups:
          - "grove.io"
        apiVersions:
          - "v1alpha1"
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - podcliques
          - podcliquescalinggroups
        scope: "Namespaced"
      - apiGroups:
          - "scheduler.grove.io"
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - podgangs
        scope: "Namespaced"
    timeoutSeconds: 10
{{- end }}